# Generated by Django 5.1.3 on 2024-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladoesquerdo',
            name='logo',
            field=models.ImageField(default=1, upload_to='img_logo_index'),
            preserve_default=False,
        ),
    ]
