# Generated by Django 5.1.3 on 2024-11-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_ladoesquerdo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Arial, sans-serif', max_length=100)),
            ],
        ),
    ]
