# Generated by Django 5.1.3 on 2024-11-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_nomeestabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomeestabelecimento',
            name='nome',
            field=models.CharField(default='Nome Do Mercado', max_length=100),
        ),
    ]
