# Generated by Django 5.1.3 on 2024-11-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_ladodireito_texto_ladoesquerdo_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladodireito',
            name='background',
        ),
        migrations.AddField(
            model_name='ladodireito',
            name='titulo',
            field=models.CharField(default='Bem Vindo!', max_length=100),
        ),
        migrations.AlterField(
            model_name='ladodireito',
            name='texto',
            field=models.TextField(default='Texto do lado direito'),
        ),
        migrations.AlterField(
            model_name='ladoesquerdo',
            name='texto',
            field=models.TextField(default='Texto do lado esquerdo'),
        ),
    ]
