# Generated by Django 5.1.3 on 2024-11-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_ladodireito_background_ladodireito_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladodireito',
            name='titulo',
        ),
    ]
