# Generated by Django 5.1.3 on 2024-11-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_ladodireito_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladodireito',
            name='titulo',
            field=models.CharField(default='Bem Vindo!', max_length=100),
        ),
    ]
