# Generated by Django 5.1.3 on 2024-11-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_ladodireito_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladodireito',
            name='background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
