# Generated by Django 5.1.3 on 2024-11-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_titulopagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_aviso', models.ImageField(upload_to='aviso_index')),
                ('altura', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=40)),
                ('texto', models.TextField(default='Texto do lado direito')),
                ('estilo_letra_titulo', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('cor_letra_titulo', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
